version: "3.9"
services:

  server:
    container_name: server-container
    build: .  
    restart: always
    environment: 
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - postgres

  postgres:
    container_name: postgres-container
    build: ./docker/postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/data/postgres
    networks:
      - postgres

volumes:
  pgdata:
    driver: local

networks:
    postgres:
      driver: bridge
